"""Add chat enhancements for mobile

Revision ID: 18d06b12a5d9
Revises: 328d4088b745
Create Date: 2025-06-16 21:30:04.380701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18d06b12a5d9'
down_revision: Union[str, None] = '328d4088b745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum types first
    messagetype_enum = sa.Enum('text', 'image', 'file', 'voice', 'location', name='messagetype')
    messagestatus_enum = sa.Enum('sent', 'delivered', 'read', name='messagestatus')
    messagetype_enum.create(op.get_bind())
    messagestatus_enum.create(op.get_bind())
    
    op.create_table('onlinestatus',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('device_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('eventmodel')
    
    # Add columns with proper handling
    op.add_column('chatmessage', sa.Column('status', messagestatus_enum, nullable=False, server_default='sent'))
    op.add_column('chatmessage', sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('chatmessage', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('chatmessage', sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('chatmessage', sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('chatmessage', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('chatmessage', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('chatmessage', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('chatmessage', sa.Column('reply_to_id', sa.Integer(), nullable=True))
    op.add_column('chatmessage', sa.Column('is_edited', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('chatmessage', sa.Column('edited_at', sa.DateTime(), nullable=True))
    op.add_column('chatmessage', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('chatmessage', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    
    # Alter column type
    op.alter_column('chatmessage', 'type',
               existing_type=sa.VARCHAR(),
               type_=messagetype_enum,
               existing_nullable=False,
               postgresql_using='type::messagetype')
    op.create_foreign_key(None, 'chatmessage', 'chatmessage', ['reply_to_id'], ['id'])
    
    # Add chatroom columns with defaults
    op.add_column('chatroom', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('chatroom', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('chatroom', sa.Column('last_message_id', sa.Integer(), nullable=True))
    op.add_column('chatroom', sa.Column('last_activity', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatroom', 'last_activity')
    op.drop_column('chatroom', 'last_message_id')
    op.drop_column('chatroom', 'is_active')
    op.drop_column('chatroom', 'updated_at')
    op.drop_constraint(None, 'chatmessage', type_='foreignkey')
    op.alter_column('chatmessage', 'type',
               existing_type=sa.Enum('text', 'image', 'file', 'voice', 'location', name='messagetype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('chatmessage', 'deleted_at')
    op.drop_column('chatmessage', 'is_deleted')
    op.drop_column('chatmessage', 'edited_at')
    op.drop_column('chatmessage', 'is_edited')
    op.drop_column('chatmessage', 'reply_to_id')
    op.drop_column('chatmessage', 'longitude')
    op.drop_column('chatmessage', 'latitude')
    op.drop_column('chatmessage', 'duration')
    op.drop_column('chatmessage', 'thumbnail_url')
    op.drop_column('chatmessage', 'file_name')
    op.drop_column('chatmessage', 'file_size')
    op.drop_column('chatmessage', 'file_url')
    op.drop_column('chatmessage', 'status')
    op.create_table('eventmodel',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('page', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('descriptions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('update_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('eventmodel_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('eventmodel_pkey'))
    )
    op.drop_table('onlinestatus')
    # ### end Alembic commands ###
