"""update model

Revision ID: 4cde1780f6d1
Revises: 8953d55ec38b
Create Date: 2025-06-06 22:21:48.897727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cde1780f6d1'
down_revision: Union[str, None] = '8953d55ec38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventmodel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventmodel',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('page', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('descriptions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('update_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('eventmodel_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('eventmodel_pkey'))
    )
    # ### end Alembic commands ###
