"""Add is_buyer column

Revision ID: 7ab9f1e0ed74
Revises: b10136eca270
Create Date: 2025-06-06 08:42:04.733405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ab9f1e0ed74'
down_revision: Union[str, None] = 'b10136eca270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventmodel')
    op.add_column('user', sa.Column('is_buyer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_buyer')
    op.create_table('eventmodel',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('page', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('descriptions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('update_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('eventmodel_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('eventmodel_pkey'))
    )
    # ### end Alembic commands ###
